### ISSUE TITLE
ns-remote実行時セグメンテーション違反エラー

### ISSUE THREAD

**Issue by tokohito** [mzyy94/ns-remote#2]
表題の通り ns-remote 実行時セグメンテーション違反が発生します。
解決方法を教えていただますでしょうか、よろしくお願いします。

```

pi@raspberrypi:~/git/ns-remote $ v4l2-ctl --list-devices
bcm2835-codec-decode (platform:bcm2835-codec):
        /dev/video10
        /dev/video11
        /dev/video12

bcm2835-isp (platform:bcm2835-isp):
        /dev/video13
        /dev/video14
        /dev/video15
        /dev/video16

unicam (platform:fe801000.csi):
        /dev/video0
        /dev/video1

pi@raspberrypi:~/git/ns-remote $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: UAC1Gadget [UAC1_Gadget], device 0: UAC1_PCM [UAC1_PCM]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

pi@raspberrypi:~/git/ns-remote $ sudo ./ns-remote
[ GSTREAMER ] shim init
[ GST ] program is linked against GStreamer 1.14.4
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x245670]

goroutine 1 [running]:
github.com/notedit/gst.(*Element).SetObject.func3(0x0, 0xa48af8, 0xa60e10)
        /home/pi/go/pkg/mod/github.com/notedit/gst@v0.0.4/element.go:216 +0x14
github.com/notedit/gst.(*Element).SetObject(0x0, 0x3f5b5e, 0x6, 0x395260, 0xcf7ef4)
        /home/pi/go/pkg/mod/github.com/notedit/gst@v0.0.4/element.go:216 +0x240
ns-remote/stream.NewVideoPipeline(0xc9f9d8, 0x3f5544)
        /home/pi/git/ns-remote/stream/video.go:23 +0xa0
ns-remote/stream.NewMediaSource(0xc9f9d8, 0xc9f9e0, 0x7)
        /home/pi/git/ns-remote/stream/source.go:28 +0x1c
main.main()
        /home/pi/git/ns-remote/main.go:30 +0x29c
```

**Comment by mzyy94** [comment]
以下のようにオプションをつけてみて動作の確認してみてください
- `sudo ./ns-remote -demo`
- `sudo ./ns-remote -audio hw:UAC1Gadget`
- `sudo ./ns-remote -video /dev/video1`

**Comment by tokohito** [comment]
回答ありがとうございます。結果は以下の通りです。

```
pi@raspberrypi:~/git/ns-remote $ v4l2-ctl --list-devices
bcm2835-codec-decode (platform:bcm2835-codec):
        /dev/video10
        /dev/video11
        /dev/video12

bcm2835-isp (platform:bcm2835-isp):
        /dev/video13
        /dev/video14
        /dev/video15
        /dev/video16

unicam (platform:fe801000.csi):
        /dev/video0
        /dev/video1

pi@raspberrypi:~/git/ns-remote $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: UAC1Gadget [UAC1_Gadget], device 0: UAC1_PCM [UAC1_PCM]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

pi@raspberrypi:~/git/ns-remote $ sudo ./ns-remote -demo
[ GSTREAMER ] shim init
[ GST ] program is linked against GStreamer 1.14.4
2021/03/31 09:58:08 State of PeerConnection-1617181088408868067: checking
2021/03/31 09:58:08 -- start sample transfer of track video
2021/03/31 09:58:08 -- start sample transfer of track audio
2021/03/31 09:58:08 State of PeerConnection-1617181088408868067: connected
※ブラウザアクセスとデモモード動作OK

pi@raspberrypi:~/git/ns-remote $ sudo ./ns-remote -audio hw:UAC1Gadget
[ GSTREAMER ] shim init
[ GST ] program is linked against GStreamer 1.14.4
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x245670]

goroutine 1 [running]:
github.com/notedit/gst.(*Element).SetObject.func3(0x0, 0xa364fbb8, 0xa364f4a0)
        /home/pi/go/pkg/mod/github.com/notedit/gst@v0.0.4/element.go:216 +0x14
github.com/notedit/gst.(*Element).SetObject(0x0, 0x3f5ba6, 0x6, 0x3952a8, 0xcf7f00)
        /home/pi/go/pkg/mod/github.com/notedit/gst@v0.0.4/element.go:216 +0x240
ns-remote/stream.NewAudioPipeline(0xc9f9d8, 0xca84b0)
        /home/pi/git/ns-remote/stream/audio.go:20 +0xa0
ns-remote/stream.NewMediaSource(0xc9f9d0, 0xc9f9d8, 0x7)
        /home/pi/git/ns-remote/stream/source.go:29 +0x30
main.main()
        /home/pi/git/ns-remote/main.go:30 +0x29c

pi@raspberrypi:~/git/ns-remote $ sudo ./ns-remote -video /dev/video1
[ GSTREAMER ] shim init
[ GST ] program is linked against GStreamer 1.14.4
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x245670]

goroutine 1 [running]:
github.com/notedit/gst.(*Element).SetObject.func3(0x0, 0x173c760, 0x173c780)
        /home/pi/go/pkg/mod/github.com/notedit/gst@v0.0.4/element.go:216 +0x14
github.com/notedit/gst.(*Element).SetObject(0x0, 0x3f5ba6, 0x6, 0x3952a8, 0x18aff00)
        /home/pi/go/pkg/mod/github.com/notedit/gst@v0.0.4/element.go:216 +0x240
ns-remote/stream.NewAudioPipeline(0x188f3c0, 0x18983c0)
        /home/pi/git/ns-remote/stream/audio.go:20 +0xa0
ns-remote/stream.NewMediaSource(0x188f3b8, 0x188f3c0, 0x7)
        /home/pi/git/ns-remote/stream/source.go:29 +0x30
main.main()
        /home/pi/git/ns-remote/main.go:30 +0x29c
```

**Comment by tokohito** [comment]
※補足
RPi4の接続環境ですが、暫定的に以下のサードパーティードック経由で接続しています。
https://www.uniqstyle.co.jp/products/Dongii/

**Comment by mzyy94** [comment]
エラーはいずれも https://github.com/mzyy94/ns-remote/blob/281b2020793df16875846a89a88db49c575b8040/stream/audio.go#L20 で出てるのでALSAデバイスの指定が失敗してるようなんですよねぇ。
gstreamerのalsa pluginが導入されていなかったりしますか？
```
sudo apt install gstreamer1.0-alsa
```

**Comment by tokohito** [comment]
ドンピシャです！alsa pluginをインストールしたらセグメンテーション違反エラーは出ずにブラウザ上でテレビモード画面と
仮想コントローラー操作ができるようになりました。ありがとうございます。

ただaudio streamががうまく転送できていないようで音声が聞こえません…まだ何か足りないのでしょうか？
```
2021/03/31 10:37:11 -- start sample transfer of track video
2021/03/31 10:37:11 -- start sample transfer of track audio
2021/03/31 10:37:11 Pull error on track audio: could not pull a sample from appsink
2021/03/31 10:37:12 State of PeerConnection-1617183431917805360: connected
sctp ERROR: 2021/03/31 10:42:45 [0x26cab40] retransmission failure: T1-init
```

**Comment by mzyy94** [comment]
alsaプラグインについてREADMEに書きそびれていたので後で記載しておきます🙇‍♂️

音声が取れない原因を想像するに、以下のいずれかが考えられます：
- ALSAデバイスのアタッチする先が異なっている
- UAC Gadgetに音声サンプルが流れてきていない

前者であれば、`sudo ./ns-remote -audio hw:UAC1Gadget`や`sudo ./ns-remote -audio hw:1,0`などで指定のデバイスを変えて改善する可能性があります。
後者であれば、 https://mzyy94.com/blog/2020/04/17/nintendo-switch-audio-uac-gadget/#%E9%9F%B3%E5%A3%B0%E5%8F%96%E3%82%8A%E8%BE%BC%E3%81%BF に沿ってUAC Gadgetに流れてきているかを確認してみると問題の切り分けができるかもしれません。

**Comment by tokohito** [comment]
sudo ./ns-remote -audio hw:UAC1Gadget で解消しました！本当にありがとうございます！！

これは完全に趣旨が違う私のわがままなんですが、画面だけns-remoteで表示して手元は物理のコントローラーで操作するために
オンスクリーン仮想ボタンを非表示にするためのツールバーもしくはns-remote自体の起動オプションなどがあると
大変ありがたいのですが、ご検討いただけないでしょうか？

**Comment by mzyy94** [comment]
おお、よかったです☺️
ひとまず解決ですね

ビュワー専用のモードは検討しているので今後アップデートで対応しますね😀
暫定対応として、以下のbookmarkletをブックマークに追加して実行することで、非表示にして対処いただけると😅

```
javascript:document.querySelector('canvas')?.style.setProperty('opacity','0')
```
